[en]
contentDir = 'content/en'
languageName = 'English'
languageCode = 'en'
weight = 10
title = "My New Hugo Site"

[zh-Hans]
contentDir = 'content/zh-Hans'
languageName = '简体中文'
languageCode = 'zh-Hans'
weight = 20
title = "我的新Hugo站点"

[fr]
contentDir = 'content/fr'
languageName = 'Français'
languageCode = 'fr'
weight = 30
title = "Mon nouveau site Hugo"
